name: main
on:
  workflow_call:
  workflow_dispatch: {}   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
       
      - name: Get project data
        env:
          ORGANIZATION: "devops-testbed"
          PROJECT_NUMBER: 1
        run: echo $ORGANIZATION $PROJECT_NUMBER
        
      - name: Add PR to project
        env:
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: echo $PR_ID

      - name: Get date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
  #Invalid workflow file: .github/workflows/org-ci-workflow.yml#L43
  #error parsing called workflow "devops-testbed/intake/.github/workflows/main.yml@main": job "job-calling-workflow" calls workflow "devops-testbed/intake/.github/workflows/reusable-workflow.yml@main", but doing so would exceed the limit on called workflow depth of 1
  #job-calling-workflow:
  #  uses: devops-testbed/intake/.github/workflows/reusable-workflow.yml@main
  job-calling-composite:
    needs: job1
    runs-on: ubuntu-latest
    steps:     
      - name: use composite devops-testbed/intake@main
        uses: devops-testbed/intake@main

      - name: use repo folder composite devops-testbed/intake/folder-action@main
        uses: devops-testbed/intake/folder-action@main
        
      - name: call devops-testbed/intake/comp-action-workflow@main
        uses: devops-testbed/intake/comp-action-workflow@main
