name: Org CI
on:
  branch_protection_rule:
    types: [created, edited, deleted]
  check_run:
    types: [created, rerequested, completed, requested_action]
  check_suite:
    types: [completed]
  create:
  delete:
  deployment:
  push:
    branches-ignore:    
      - 'mona/octocat'
      - 'releases/**-alpha'
    tags-ignore:        
      - v2
      - v1.*
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: 
      - "main"
      - '!releases/**-alpha'
    paths:
      - '**.js'
    tags:        
      - v2
      - v1.*
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'
  workflow_call:
    inputs:
      projectid:
        description: 'Project'
        default: '1'
        required: false
        type: string
jobs:
  call-rswflw-repo-workflow:
    uses: devops-testbed/intake/.github/workflows/main.yml@main
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
  build:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: devops-testbed/intake/.github/workflows/main.yml@main
      - name: Print the input name to STDOUT
        run: echo The projectid is ${{ inputs.projectid }}
      - name: Check token blanked
        run: echo The token is ${{ secrets.GITHUB_TOKEN }}
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: debug
        env:
          GH_EVENT: ${{ toJson(github) }}
        run: echo ${GH_EVENT}
